"""Adapters de input/output por task.

Padrão:
def <task_id>_input_func(input_data: dict) -> dict:
    # extrai kwargs para a task
    return input_data

def <task_id>_output_func(input_data: dict, result: str) -> dict:
    # parseia o resultado retornado pelo CrewAI
    return {"raw": result}
"""
from typing import Any, Dict


# ─── Bindings de tools (deterministic, extraído do agent_task_spec) ───
AGENT_TOOLS = {
    'administrador_agent': ['database_tool', 'embedding_tool'],
    'agenda_medico_agent': ['database_tool', 'embedding_tool'],
    'encaminhamento_agent': ['database_tool', 'embedding_tool'],
    'especialista_cardiologia_agent': ['database_tool', 'embedding_tool'],
    'especialista_gastroenterologia_agent': ['database_tool', 'embedding_tool'],
    'especialista_pediatria_agent': ['database_tool', 'embedding_tool'],
    'fallback_agent': ['database_tool', 'embedding_tool'],
    'kpi_dashboard_agent': ['database_tool', 'embedding_tool'],
    'medico_agent': ['database_tool', 'embedding_tool'],
    'recepcionista_agent': ['database_tool', 'embedding_tool'],
    'registro_prontuario_agent': ['database_tool', 'embedding_tool'],
    'triagem_hub_agent': ['database_tool', 'embedding_tool'],
}

TASK_TOOLS = {
    'atualizar_paciente': ['database_tool', 'embedding_tool'],
    'cadastrar_paciente': ['database_tool', 'embedding_tool'],
    'consulta_medica': ['database_tool', 'embedding_tool'],
    'criar_encaminhamento': ['database_tool', 'embedding_tool'],
    'fallback_manual': ['database_tool', 'embedding_tool'],
    'gerir_administrador': ['database_tool', 'embedding_tool'],
    'gerir_agenda_medico': ['database_tool', 'embedding_tool'],
    'pre_atendimento_cardiologia': ['database_tool', 'embedding_tool'],
    'pre_atendimento_gastroenterologia': ['database_tool', 'embedding_tool'],
    'pre_atendimento_pediatria': ['database_tool', 'embedding_tool'],
    'registrar_prontuario': ['database_tool', 'embedding_tool'],
    'triagem_agentiva': ['database_tool', 'embedding_tool'],
    'visualizar_kpis': ['database_tool', 'embedding_tool'],
}


# ─── helper de normalização de campos de lista (auto-gerado pelo LangNet) ───
def _as_list(v):
    """Normaliza um campo de lista: string 'a, b' -> ['a','b']; lista -> lista; None -> [].
    Torna os adapters determinísticos robustos a input string (evita iterar caractere)."""
    if v is None:
        return []
    if isinstance(v, list):
        return v
    if isinstance(v, str):
        return [x.strip() for x in v.split(',') if x.strip()]
    return [v]


def _hoje():
    """Data de hoje (YYYY-MM-DD) — default para colunas de data NOT NULL ausentes
    no input, evitando '1048 Column ... cannot be null'."""
    from datetime import date
    return date.today().isoformat()


# ─── Deterministic CRUD adapters (auto-generated by LangNet) ───
# Cada função <task>_deterministic(input_data) executa os passos SQL da
# description da task DIRETO no MySQL, sem chamar LLM/CrewAI. O
# websocket_server usa essas funções por padrão quando existem, caindo
# de volta pro agente CrewAI só quando não há função deterministic.
# Tasks geradas: cadastrar_paciente, atualizar_paciente, criar_encaminhamento, registrar_prontuario
def cadastrar_paciente_deterministic(input_data):
    """Auto-generated by LangNet: executes cadastrar_paciente's CRUD steps
    directly against MySQL, bypassing the CrewAI agent."""
    import os
    import mysql.connector
    conn = mysql.connector.connect(
        host=os.getenv('DB_HOST', 'localhost'),
        port=int(os.getenv('DB_PORT', '3306')),
        user=os.getenv('DB_USER', 'root'),
        password=os.getenv('DB_PASSWORD', ''),
        database=os.getenv('DB_NAME', ''),
    )
    try:
        cur = conn.cursor(dictionary=True)
        cur.execute('INSERT INTO pacientes(nome, cpf, data_nascimento, contato, convenio) VALUES(%s, %s, %s, %s, %s)', [input_data.get('nome'), input_data.get('cpf'), (input_data.get('data_nascimento') or _hoje()), input_data.get('contato'), input_data.get('convenio')])
        cur.execute('SELECT id FROM pacientes WHERE cpf=%s ORDER BY created_at DESC LIMIT 1', [input_data.get('cpf')])
        _row = cur.fetchone()
        paciente_id = _row['id'] if _row else None
        cur.execute("INSERT INTO consentimentos(paciente_id, data_hora, versao_termo) VALUES(%s, NOW(), 'v1')", [paciente_id])
        _result = {'status': 'sucesso', 'paciente_id': paciente_id}
        conn.commit()
        return _result
    except Exception as _e:
        conn.rollback()
        return {'status': 'erro', 'error': str(_e)}
    finally:
        try: cur.close()
        except Exception: pass
        conn.close()


def atualizar_paciente_deterministic(input_data):
    """Auto-generated by LangNet: executes atualizar_paciente's CRUD steps
    directly against MySQL, bypassing the CrewAI agent."""
    import os
    import mysql.connector
    conn = mysql.connector.connect(
        host=os.getenv('DB_HOST', 'localhost'),
        port=int(os.getenv('DB_PORT', '3306')),
        user=os.getenv('DB_USER', 'root'),
        password=os.getenv('DB_PASSWORD', ''),
        database=os.getenv('DB_NAME', ''),
    )
    try:
        cur = conn.cursor(dictionary=True)
        cur.execute('UPDATE pacientes SET nome=%s, cpf=%s, data_nascimento=%s, contato=%s, convenio=%s, historico=%s, status=%s WHERE id=%s', [input_data.get('nome'), input_data.get('cpf'), (input_data.get('data_nascimento') or _hoje()), input_data.get('contato'), input_data.get('convenio'), input_data.get('historico'), input_data.get('status'), input_data.get('paciente_id')])
        cur.execute("INSERT INTO consentimentos(paciente_id, data_hora, versao_termo) VALUES(%s, NOW(), 'v1')", [input_data.get('paciente_id')])
        _result = {'status': 'sucesso'}
        conn.commit()
        return _result
    except Exception as _e:
        conn.rollback()
        return {'status': 'erro', 'error': str(_e)}
    finally:
        try: cur.close()
        except Exception: pass
        conn.close()


def criar_encaminhamento_deterministic(input_data):
    """Auto-generated by LangNet: executes criar_encaminhamento's CRUD steps
    directly against MySQL, bypassing the CrewAI agent."""
    import os
    import mysql.connector
    conn = mysql.connector.connect(
        host=os.getenv('DB_HOST', 'localhost'),
        port=int(os.getenv('DB_PORT', '3306')),
        user=os.getenv('DB_USER', 'root'),
        password=os.getenv('DB_PASSWORD', ''),
        database=os.getenv('DB_NAME', ''),
    )
    try:
        cur = conn.cursor(dictionary=True)
        cur.execute('SELECT id FROM medicos WHERE especialidade_id=%s ORDER BY created_at ASC LIMIT 1', [input_data.get('especialidade_id')])
        _row = cur.fetchone()
        medico_id = _row['id'] if _row else None
        cur.execute('SELECT atendimento_id FROM prontuarios WHERE paciente_id=%s ORDER BY created_at DESC LIMIT 1', [input_data.get('paciente_id')])
        _row = cur.fetchone()
        atendimento_id = _row['id'] if _row else None
        cur.execute("INSERT INTO encaminhamentos(atendimento_id, especialidade_id, medico_id, prioridade) VALUES(%s, %s, %s, 'normal')", [atendimento_id, input_data.get('especialidade_id'), medico_id])
        cur.execute('SELECT id FROM encaminhamentos WHERE atendimento_id=%s AND especialidade_id=%s ORDER BY created_at DESC LIMIT 1', [atendimento_id, input_data.get('especialidade_id')])
        _row = cur.fetchone()
        encaminhamento_id = _row['id'] if _row else None
        cur.execute('UPDATE prontuarios SET encaminhamento_id=%s WHERE atendimento_id=%s', [encaminhamento_id, atendimento_id])
        _result = {'status': 'sucesso', 'medico_id': medico_id, 'atendimento_id': atendimento_id, 'encaminhamento_id': encaminhamento_id}
        conn.commit()
        return _result
    except Exception as _e:
        conn.rollback()
        return {'status': 'erro', 'error': str(_e)}
    finally:
        try: cur.close()
        except Exception: pass
        conn.close()


def registrar_prontuario_deterministic(input_data):
    """Auto-generated by LangNet: executes registrar_prontuario's CRUD steps
    directly against MySQL, bypassing the CrewAI agent."""
    import os
    import mysql.connector
    conn = mysql.connector.connect(
        host=os.getenv('DB_HOST', 'localhost'),
        port=int(os.getenv('DB_PORT', '3306')),
        user=os.getenv('DB_USER', 'root'),
        password=os.getenv('DB_PASSWORD', ''),
        database=os.getenv('DB_NAME', ''),
    )
    try:
        cur = conn.cursor(dictionary=True)
        cur.execute('INSERT INTO prontuarios(paciente_id, atendimento_id, triagem, pre_diagnostico_id, encaminhamento_id, resumo_medico) VALUES(%s, %s, %s, %s, %s, %s)', [input_data.get('paciente_id'), input_data.get('atendimento_id'), input_data.get('triagem'), input_data.get('pre_diagnostico_id'), input_data.get('encaminhamento_id'), input_data.get('resumo_medico')])
        cur.execute('SELECT id FROM prontuarios WHERE paciente_id=%s AND atendimento_id=%s ORDER BY created_at DESC LIMIT 1', [input_data.get('paciente_id'), input_data.get('atendimento_id')])
        _row = cur.fetchone()
        prontuario_id = _row['id'] if _row else None
        _result = {'status': 'sucesso', 'prontuario_id': prontuario_id}
        conn.commit()
        return _result
    except Exception as _e:
        conn.rollback()
        return {'status': 'erro', 'error': str(_e)}
    finally:
        try: cur.close()
        except Exception: pass
        conn.close()

