# -*- coding: utf-8 -*-
"""Resumo de uma ou duas linhas por lâmina da V15, para o roteiro do coordenador."""
R = [
"Capa da palestra: Engenharia de IA e Desenvolvimento Orientado a Especificação.",
"Apresentação do palestrante: formação, carreira em engenharia de software, ensino e inteligência artificial.",
"Sumário: o histórico da IA e os doze blocos, agrupados em Fundamentos, Engenharia e Método.",
"Divisor da seção Histórico da IA.",
"Setenta anos de IA em um minuto: do Perceptron e do teste de Turing até os agentes de hoje.",
"Abertura do Bloco 1 — Machine Learning.",
"Aprendizado supervisionado (com resposta conhecida) e não supervisionado (descobre grupos sozinho).",
"As seis etapas de um projeto de Machine Learning, do dado à avaliação.",
"Visualizar e preparar os dados: distribuição, correlação, limpeza e escala.",
"Separar treino e teste, e escolher o modelo por busca em grade.",
"Treinar e avaliar: o sobreajuste e como evitá-lo.",
"Como se mede um classificador: matriz de confusão, sensibilidade, especificidade e curva ROC.",
"O ferramental: Python, Jupyter/Colab, scikit-learn, TensorFlow/PyTorch, pandas.",
"K Vizinhos Mais Próximos: classifica pela votação dos casos mais parecidos (figura com K=3).",
"Regressão Linear: a reta que melhor prevê um número (figura renda × IDH).",
"Regressão Logística: o limite de decisão e a sigmoide, que dá a probabilidade de cada classe.",
"Árvore de Decisão: uma sequência de perguntas que divide o plano em regiões.",
"Random Forest: muitas árvores votando, com fronteira mais estável que a de uma árvore só.",
"Máquina de Vetores de Suporte: a separação de maior margem, com o truque de passar para 3D.",
"K-Means: agrupamento sem rótulos, passo a passo (sortear centros, agrupar, recalcular).",
"Vídeo (16 min): notebook do pipeline de Machine Learning sobre exames de câncer de mama.",
"Abertura do Bloco 2 — Deep Learning e Transfer Learning.",
"O neurônio artificial: entradas, pesos, soma e função de ativação.",
"A rede de múltiplas camadas: entrada, camadas ocultas e saída (figura da apresentação-base).",
"Como a rede aprende: retropropagação do erro e ajuste dos pesos.",
"Redes convolucionais: o caminho da imagem (bordas → partes → objetos) e a arquitetura (convolução, pooling, flatten, camada densa).",
"Transfer Learning: reaproveitar uma rede pré-treinada, congelando camadas e treinando só as finais.",
"Vídeo (10 min): notebook de deep learning com Transfer Learning (VGG16) em tomografias de COVID-19.",
"Abertura do Bloco 3 — Inteligência Artificial na saúde.",
"Prognóstico e avaliação de risco: escores, sobrevivência e modelo de Cox.",
"Diagnóstico: sistemas especialistas, modelos clínicos e redes para imagens médicas.",
"Tratamento: estimar a resposta a cada opção terapêutica; o modelo apoia, não decide.",
"Vídeo (7 min): notebook de IA na medicina — diagnóstico por raio-X, avaliação, prognóstico e tratamento.",
"Abertura do Bloco 4 — Modelos de linguagem e Transformer.",
"O que é um modelo de linguagem: prever o próximo token.",
"De onde veio o Transformer: o artigo “Attention Is All You Need” (2017).",
"A arquitetura do Transformer: codificador, decodificador e matriz de atenção.",
"Anatomia da atenção: consulta, chave e valor, e o custo que cresce com o tamanho da entrada.",
"Escala: o que ela trouxe, a Mistura de Especialistas (MoE) e o que não resolveu.",
"Inferência: temperatura, cache e quantização.",
"Infraestrutura: o que é uma GPU, as placas do mercado e onde treinar (Colab, AWS, Google Cloud).",
"Exemplo de infraestrutura local para desenvolvimento de IA: máquina principal e máquina de apoio.",
"Panorama dos modelos proprietários (OpenAI, Anthropic, Google, xAI) e quem é melhor em cada tarefa.",
"Panorama dos modelos abertos (DeepSeek, Qwen, Kimi, MiniMax) e quem é melhor em cada tarefa.",
"A escada da adaptação: instrução, contexto, ferramentas e, por último, ajuste fino.",
"Fine-tuning de modelos: como se faz, e o LoRA/QLoRA para treinar menos de 1% dos pesos.",
"Vídeo (11 min): notebook que constrói um LLM do tipo GPT do zero, com pré-treino e ajustes finos.",
"Vídeo (4 min): notebook de fine-tuning com LoRA de um modelo de 7B sobre controle de infecção.",
"Abertura do Bloco 5 — Agentes.",
"De modelo para agente: o que muda é o laço de ação.",
"Definição operacional de agente: objetivo, contexto, ferramentas, memória e critério de parada.",
"O laço agêntico: pensar, pedir a ferramenta, executar, observar.",
"Uso de ferramenta sem framework: o laço inteiro em vinte linhas de Python.",
"Os padrões de composição: encadeamento, roteamento e paralelismo (e outros três).",
"Multiagente: quando compensa e quando não.",
"Por que agentes falham em produção: o erro que se compõe a cada passo.",
"Abertura do Bloco 6 — Engenharia de contexto.",
"De “prompt” para engenharia de contexto: o que entra na janela do modelo.",
"RAG — Recuperação Aumentada por Geração: buscar trechos e responder com fonte.",
"Busca convencional (por palavra) × busca vetorial (por sentido, com embeddings).",
"Tipos e técnicas de RAG: fatiamento, embeddings, índice vetorial (FAISS), busca híbrida, filtros e reranking.",
"RAG na prática: o fluxo em código, dos documentos à resposta.",
"Onde o RAG quebra: o fatiamento que corta uma regra ao meio.",
"Saída estruturada e proteções (guardrails).",
"Vídeo (6 min): notebook de RAG — um assistente de controle de infecção hospitalar.",
"Abertura do Bloco 7 — Frameworks de agentes.",
"O critério de leitura: quatro perguntas para avaliar qualquer framework.",
"Comparativo dos frameworks, e a opinião contrária.",
"LangChain: peças prontas ligadas numa cadeia (exemplo simples e com RAG).",
"CrewAI: agentes, tarefas e equipe declarados em YAML.",
"LangGraph: estado, nós, arestas e condição (código e diagrama).",
"AutoGen: dois agentes que conversam até o trabalho ser aprovado.",
"Outros: OpenAI Agents SDK e Claude Agent SDK.",
"Vídeo (10 min): notebook com CrewAI — qualificação de leads e e-mail de vendas.",
"Vídeo (4 min): notebook com AutoGen — residente e infectologista revisam pareceres da CCIH.",
"Abertura do Bloco 8 — Agentes para produção de código.",
"Mudou a unidade de trabalho: da linha de código para a tarefa descrita.",
"Claude Code: comandos e recursos (skills, subagentes, equipes, MCP, modo não interativo).",
"Codex: os mesmos recursos, para comparar com o Claude Code.",
"Cursor e o panorama dos editores com agente.",
"Abertura do Bloco 9 — Protocolos e contratos.",
"Os protocolos um a um: MCP, A2A e OKF.",
"O mapa: MCP no eixo vertical; A2A e OKF no horizontal.",
"Conhecimento em formato aberto: o OKF em detalhe.",
"Abertura do Bloco 10 — Specification-Driven Development (SDD).",
"O problema: Vibe Coding × SDD.",
"A inversão: a especificação vira o artefato principal; o código se regenera.",
"Anatomia de uma especificação útil: requisitos verificáveis.",
"Da especificação ao código: a cadeia de rastreabilidade.",
"Onde o SDD encontra os agentes: um agente por etapa, com portão entre elas.",
"O artefato regulatório sai de graça: rastreabilidade como subproduto.",
"Antipadrões: como o método morre na prática.",
"Abertura do Bloco 11 — LangNet: um framework para SDD automatizado.",
"Dois lados: a fábrica (LangNet) e a máquina (a aplicação gerada).",
"As etapas do LangNet e o ritual comum a todas: origem, geração, refino e aprovação.",
"Do documento aos requisitos: extração, inferência e procedência de cada item.",
"A especificação funcional: casos de uso, fluxos de exceção e esboço da tela.",
"O modelo de dados e a correção por conversa.",
"A interface e o protótipo navegável.",
"Ferramentas, agentes e tarefas, cada um com a sua origem.",
"A rede de Petri: a orquestração das tarefas, com token e sincronização.",
"Casos de teste pelo grafo de causa e efeito, e a geração do código.",
"A aplicação rodando e a bancada de execução.",
"O exemplo: BioByte, vigilância de infecção hospitalar — contexto e escopo.",
"Vídeo (10 min): o LangNet percorrendo todas as etapas do pipeline sobre o BioByte.",
"Vídeo (7 min): o app de validação — documentos do projeto, tutorial guiado e trilha de correções.",
"Vídeo (3 min): o app de validação rápida — o sistema executa os casos de uso e o validador decide.",
"Divisor do Fechamento.",
"As três conclusões da palestra.",
"Encerramento: a frase da tese e os agradecimentos.",
]
